"use client";

import { useState } from "react";
import Image from "next/image";

const demos = [
  { title: "How Google Solved Big Data on Broken Hardware (GFS Explained)", youtubeId: "ADC-lnf7i0E", minutes: 15 },
  { title: "Dremel: Interactive Analysis", youtubeId: "7wCx8iQHaRM", minutes: 12 },
  { title: "MapReduce", youtubeId: "KZvrVlAYqGc", minutes: 12 },
];

export default function DemoVideos() {
  const [playingId, setPlayingId] = useState<string | null>(null);

  return (
    <section id="demo" className="bg-gray-100 px-6 py-20">
      <div className="mx-auto max-w-6xl">
        <h2 className="text-center text-2xl font-bold text-foreground md:text-3xl">
          See it in action
        </h2>
        <p className="mt-3 text-center text-gray-500">
          Real papers, real videos, generated by stemvid.ai
        </p>

        <div className="mt-12 grid gap-8 sm:grid-cols-2 lg:grid-cols-3">
          {demos.map((demo) => {
            const isPlaying = playingId === demo.youtubeId;
            return (
              <div
                key={demo.title}
                className="overflow-hidden rounded-lg bg-background shadow-sm transition-shadow hover:shadow-md"
              >
                <div className="relative aspect-video bg-gray-200">
                  {isPlaying ? (
                    <iframe
                      src={`https://www.youtube.com/embed/${demo.youtubeId}?autoplay=1`}
                      title={demo.title}
                      allow="autoplay; encrypted-media; picture-in-picture"
                      allowFullScreen
                      className="absolute inset-0 h-full w-full"
                    />
                  ) : (
                    <button
                      type="button"
                      onClick={() => setPlayingId(demo.youtubeId)}
                      aria-label={`Play ${demo.title}`}
                      className="group absolute inset-0 h-full w-full"
                    >
                      <Image
                        src={`https://img.youtube.com/vi/${demo.youtubeId}/hqdefault.jpg`}
                        alt={demo.title}
                        fill
                        sizes="(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw"
                        className="object-cover"
                      />
                      <div className="absolute inset-0 flex items-center justify-center bg-black/20 transition-colors group-hover:bg-black/30">
                        <div className="flex h-14 w-14 items-center justify-center rounded-full bg-white/90">
                          <svg
                            viewBox="0 0 24 24"
                            className="ml-1 h-6 w-6 fill-foreground"
                            aria-hidden="true"
                          >
                            <path d="M8 5v14l11-7z" />
                          </svg>
                        </div>
                      </div>
                    </button>
                  )}
                </div>
                <div className="p-4">
                  <h3 className="font-semibold text-foreground">
                    {demo.title}
                  </h3>
                  <p className="mt-1 text-xs text-gray-500">
                    Generated by stemvid.ai in {demo.minutes} minutes
                  </p>
                </div>
              </div>
            );
          })}
        </div>

        <div className="mt-10 text-center">
          <a
            href="https://www.youtube.com/channel/UC98o_DYaxmePKq6W2gA0WQQ"
            target="_blank"
            rel="noopener noreferrer"
            className="text-sm font-medium text-teal hover:underline"
          >
            Watch more on our YouTube channel &rarr;
          </a>
        </div>
      </div>
    </section>
  );
}
