const demos = [
  { title: "Attention Is All You Need" },
  { title: "Dremel: Interactive Analysis" },
  { title: "MapReduce" },
];

export default function DemoVideos() {
  return (
    <section id="demo" className="bg-gray-100 px-6 py-20">
      <div className="mx-auto max-w-6xl">
        <h2 className="text-center text-2xl font-bold text-foreground md:text-3xl">
          See it in action
        </h2>
        <p className="mt-3 text-center text-gray-500">
          Real papers, real videos, generated by stemvid.ai
        </p>

        <div className="mt-12 grid gap-8 sm:grid-cols-2 lg:grid-cols-3">
          {demos.map((demo) => (
            <div key={demo.title} className="overflow-hidden rounded-lg bg-background shadow-sm">
              <div className="flex aspect-video items-center justify-center bg-gray-200">
                <span className="text-sm text-gray-500">
                  Video coming soon
                </span>
              </div>
              <div className="p-4">
                <h3 className="font-semibold text-foreground">
                  {demo.title}
                </h3>
                <p className="mt-1 text-xs text-gray-500">
                  Generated by stemvid.ai in 12 minutes
                </p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
