import { render, screen, fireEvent } from "@testing-library/react";
import DemoVideos from "@/components/landing/DemoVideos";

const GFS_TITLE = "How Google Solved Big Data on Broken Hardware (GFS Explained)";

describe("DemoVideos", () => {
  it("renders all three demo titles", () => {
    render(<DemoVideos />);
    expect(screen.getByText(GFS_TITLE)).toBeInTheDocument();
    expect(screen.getByText("Dremel: Interactive Analysis")).toBeInTheDocument();
    expect(screen.getByText("MapReduce")).toBeInTheDocument();
  });

  it("shows generation time for each demo", () => {
    render(<DemoVideos />);
    expect(
      screen.getByText("Generated by stemvid.ai in 15 minutes")
    ).toBeInTheDocument();
    const twelveMinuteCaptions = screen.getAllByText(
      "Generated by stemvid.ai in 12 minutes"
    );
    expect(twelveMinuteCaptions).toHaveLength(2);
  });

  it("renders a thumbnail image for each demo", () => {
    render(<DemoVideos />);
    expect(screen.getByAltText(GFS_TITLE)).toBeInTheDocument();
    expect(screen.getByAltText("Dremel: Interactive Analysis")).toBeInTheDocument();
    expect(screen.getByAltText("MapReduce")).toBeInTheDocument();
  });

  it("does not load any YouTube iframe before a demo is clicked", () => {
    render(<DemoVideos />);
    expect(document.querySelector("iframe")).not.toBeInTheDocument();
  });

  it("plays the correct video inline when its thumbnail is clicked", () => {
    render(<DemoVideos />);
    fireEvent.click(screen.getByRole("button", { name: "Play MapReduce" }));
    const iframe = document.querySelector("iframe");
    expect(iframe).toBeInTheDocument();
    expect(iframe).toHaveAttribute(
      "src",
      "https://www.youtube.com/embed/KZvrVlAYqGc?autoplay=1"
    );
  });

  it("only plays one video at a time", () => {
    render(<DemoVideos />);
    fireEvent.click(screen.getByRole("button", { name: "Play MapReduce" }));
    fireEvent.click(screen.getByRole("button", { name: `Play ${GFS_TITLE}` }));
    const iframes = document.querySelectorAll("iframe");
    expect(iframes).toHaveLength(1);
    expect(iframes[0]).toHaveAttribute(
      "src",
      "https://www.youtube.com/embed/ADC-lnf7i0E?autoplay=1"
    );
  });
});
