import { render, screen } from "@testing-library/react";
import DemoVideos from "@/components/landing/DemoVideos";

describe("DemoVideos", () => {
  it("renders all three demo titles", () => {
    render(<DemoVideos />);
    expect(screen.getByText("Attention Is All You Need")).toBeInTheDocument();
    expect(screen.getByText("Dremel: Interactive Analysis")).toBeInTheDocument();
    expect(screen.getByText("MapReduce")).toBeInTheDocument();
  });

  it("shows generation time for each demo", () => {
    render(<DemoVideos />);
    const captions = screen.getAllByText("Generated by stemvid.ai in 12 minutes");
    expect(captions).toHaveLength(3);
  });

  it("links each demo to its real YouTube video, opened in a new tab", () => {
    render(<DemoVideos />);
    const expected: Record<string, string> = {
      "Attention Is All You Need": "https://youtu.be/z-q1aw_2LWY",
      "Dremel: Interactive Analysis": "https://youtu.be/7wCx8iQHaRM",
      MapReduce: "https://youtu.be/KZvrVlAYqGc",
    };
    const links = screen.getAllByRole("link");
    expect(links).toHaveLength(3);
    for (const link of links) {
      const title = link.querySelector("h3")?.textContent ?? "";
      expect(link).toHaveAttribute("href", expected[title]);
      expect(link).toHaveAttribute("target", "_blank");
      expect(link).toHaveAttribute("rel", expect.stringContaining("noopener"));
    }
  });

  it("renders a thumbnail image for each demo", () => {
    render(<DemoVideos />);
    expect(screen.getByAltText("Attention Is All You Need")).toBeInTheDocument();
    expect(screen.getByAltText("Dremel: Interactive Analysis")).toBeInTheDocument();
    expect(screen.getByAltText("MapReduce")).toBeInTheDocument();
  });
});
